### ISSUE TITLE
I wannna simulate  flow around  a 3D square cylinder, but I make some mistakes.

### ISSUE THREAD

**Issue by StevenChow9527** [xcompact3d/Incompact3d#100]
I meet some problems that I cannot figure out. I want to use the incompact3d code to simulate  flow around  a 3D square cylinder. I use the "cylinder" module and then  my domain is xlx=24,yly=8.zlz=3. The length and width of the square cylinder are 2 and 1,respectively. The cex and cey of the square cylinder are 8 and 1, respectively. The X left and right for the volume control are 7.0 and 9.0, respectively.  The Y bottom and top for the volume control are 0 and 2.5, respectively. But there are some mistakes. After the caculation, the outcome is the following picture.  The vort except the square cylinder is no changing, it is always close to zero. The inflow and outflow speed are 0.05, and the Re is 300.
The changes in the code has been put in the file in the terms of screenshots. 
[新建 Microsoft Word 文档 (3).docx](https://github.com/xcompact3d/Incompact3d/files/8932890/Microsoft.Word.3.docx)

**Comment by pbartholomew08** [comment]
Does the velocity field look reasonable?

**Comment by slaizet** [comment]
Your inlet velocity is incorrect, why did you use 0.05 and not 1 as for the cylinder? The Reynolds is based on the freestream velocity so your actual Reynolds number is 15.

Best,

Sylvain

**Comment by wWL2771140158** [comment]
Hello, I want to realize the linear motion of the three-dimensional sphere in the Cylinder module, but I can't describe the shape of the three-dimensional sphere. The code is as follows. Can you give me some help?
![image](https://user-images.githubusercontent.com/103632822/191155618-90e84950-8f82-4110-a47d-f07e9e52ff88.png)

**Comment by mathrack** [comment]
> Hello, I want to realize the linear motion of the three-dimensional sphere in the Cylinder module, but I can't describe the shape of the three-dimensional sphere. The code is as follows. Can you give me some help?

Please do not pollute an open issue with unrelated questions. It looks like you are having trouble using the code. Please use the [Discussions](https://github.com/xcompact3d/Incompact3d/discussions) section.

**Comment by StevenChow9527** [comment]
You could try to change the "zm=zp(k)" into "zm=real(k-1,mytype)*dz". Because I can not use the computer to check the code now, I would contact you at the first time if I could use my computer to see the code.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xcompact3d/Incompact3d] I wannna simulate  flow around  a 3D square cylinder, but I make some mistakes. (Issue #100)





 
Hello, I want to realize the linear motion of the three-dimensional sphere in the Cylinder module, but I can't describe the shape of the three-dimensional sphere. The code is as follows. Can you give me some help?

**Comment by wWL2771140158** [comment]
Thank you so much! I'm trying your suggestion, can you give me your email so I can ask you some questions? I would be very honored if possible, thanks again for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xcompact3d/Incompact3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xcompact3d/Incompact3d] I wannna simulate  flow around  a 3D square cylinder, but I make some mistakes. (Issue #100)





 You could try to change the "zm=zp(k)" into "zm=real(k-1,mytype)*dz". Because I can not use the computer to check the code now, I would contact you at the first time if I could use my computer to see the code. 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年9月20日(星期二) 上午10:43 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [xcompact3d/Incompact3d] I wannna simulate  flow around  a 3D square cylinder, but I make some mistakes. (Issue #100) 
 
 
 
 
 
   
 Hello, I want to realize the linear motion of the three-dimensional sphere in the Cylinder module, but I can't describe the shape of the three-dimensional sphere. The code is as follows. Can you give me some help?
