### ISSUE TITLE
Modifying Taylor-Green-Vortex code to Flow over flat plate

### ISSUE THREAD

**Issue by rahulagrawal29** [xcompact3d/Incompact3d#19]
Hi

I am trying to simulate a flow over flat plate analysis using due modifications on Taylor-Green-Vortex code .
Using the grep command on terminal, I realized the places where ncly==1 and ncly==2 is being utilized in the code, such as schemes.f90, filter.f90, poison.f90 etc. 
Now, in order to change the code to flat plate situation, I am re-coding the parts with ncly==2 conditions at the bottom and ncly==1 conditions at the top. 
I am naming it to be a new ncly==3 condition.

Can anyone here guide me as to if this approach is correct ? Or do I need to make changes only to dery,deryy part of the code. 

Thanks 

Rahul Agrawal

**Comment by fschuch** [comment]
The code is already prepared to make different boundary conditions, please, take a look at [New Features](https://github.com/xcompact3d/Incompact3d/wiki/New-Features). You just need to set `ncly1=2` and `nclyn=1`.

Best regards,
Felipe.

**Comment by rahulagrawal29** [comment]
As far as I could see, there was no BC file for boundary layer flow in the set of files.
How do I use these conditions then ?


Regards

Rahul

**Comment by ricardofrantz** [comment]
Just use as an example the [BC-Channel-flow.f90](https://github.com/xcompact3d/Incompact3d/blob/master/BC-Channel-flow.f90) from lines 65 to 78 and update your BC-.f90 and BC-.prm. 

You don't need to change anything else as the convdiff and pre_correc are programmed to work with any combination you choose as fas as you don't try something crazy like 0x or x0.

Why you choose to start you customized flow configuration from the BC-TGV.f90 instead of BC-Cylinder.f90 or even BC-Channel-flow.f90?

Let us know from your progress,
R.

**Comment by rahulagrawal29** [comment]
Dear Ricardo

Sorry for the naive comment but this is what I am trying.

I had been using the TGV code files from the website, incompact3d.com for my work on TGV problem. Now I am supposed to shift to a flat plate problem. 
What I was trying was to change all the files which included some condition of ncly=1 or 2 to ncly=3. 

Based on the comment you wrote above, should I be changing some code in BC-TGV.f90 based on lines 65-78 of BC-Channel-Flow.f90 and similarly for BC-TGV.prm from BC-Channel-Flow.prm 


Thanks

Rahul
