### ISSUE TITLE
restriction on nx,ny,nz verses the number of processors

### ISSUE THREAD

**Issue by igalts1** [xcompact3d/Incompact3d#27]
Is there a restriction on nx,ny,nz verses the number of processors (besides the periodic BC restriction)?
when running the cylinder case with different number of procs, I get:
DIV U* max mean=  -1609.000                NaN
  ***** Using the FFTW (version 3.x) engine *****
  DIV U  max mean=  -1609.000                NaN
 U,V,W min=   1609.000       1609.000       1609.000    
 U,V,W max=  -1609.000      -1609.000      -1609.000    
Velocity diverged! FATALITY!

**Comment by ricardofrantz** [comment]
Here is a list of the recommended number of points (-1 if periodic the given direction is periodic): 7 (if jLES=0) 9 (if jLES=1, due to the extra stencil) 11 13 17 19 21 25 31 33 37 41 49 51 55 61 65 73 81 91 97 101 109 121 129 145 151 161 163 181 193 201 217 241 251 257 271 289 301 321 325 361 385 401 433 451 481 487 501 513 541 577 601 641 649 721 751 769 801 811 865 901 961 973 1001 1025 1081 1153 1201 1251 1281 1297 1351 1441 1459 1501 1537 1601 1621 1729 1801 1921 1945 2001 2049 2161 2251 2305 2401 2431 2501 2561 2593 2701 2881 2917 3001 3073 3201 3241 3457 3601 3751 3841 3889 4001 4051 4097 4321 4375 4501 4609 4801 4861 5001 5121 5185 5401 5761 5833 6001 6145 6251 6401 6481 6751 6913 7201 7291 7501 7681 7777 8001 8101 8193 8641 8749 9001 9217 9601 9721 enough...
