### ISSUE TITLE
understanding the forcing term in channel flow

### ISSUE THREAD

**Issue by polivucci** [xcompact3d/Incompact3d#37]
Hi all,

I'm doing a DNS of the classic channel flow.
The forcing term (be it const-flow-rate or const-press-grad) is calculated and applied to the velocity field
by the subroutine `channel(...)` which is called by `boundary_conditions(...)` at the beginning of each iteration.
For instance taking const-flow-rate, the velocity correction is (U<sub>b</sub><sup>n</sup> - 2/3) and the corresponding pressure gradient would be f<sup>n+1</sup>=(U<sub>b</sub><sup>n</sup> - 2/3)/&Delta;t (no substeps).

Why do we need to apply the forcing before `convdiff(...)` ? 
This is not the same as casting f<sup>n+1</sup> into the RHS of the equations when executing  `intt(...)` as I was naively expecting.

In the old version of incompact3d, the correction was applied as the last step of the iteration: no consequences on the numerics but what about the output data from `visu.f90`?

Thank you

**Comment by fschuch** [comment]
Hi,

Your observation is correct, the `call channel()` was the last step of the iteration in the last version. It was moved just in order get a better compatibility with respect to all possible flow configurations that are available in the new version, since `boundary_conditions(...)` is defined for each case.

This change has no impact in the numeric aspect, and probably no consequence for the output data and visualization, because the forcing term is really small.

Best regards,
FS

**Comment by polivucci** [comment]
Hi Felipe,

many thanks for your answer.
Do you have any suggestion on my other point?
That is first applying the press grad and then calculating conv/diff terms.
I have seen that other fractional-step methods e.g. Chorin(1968)
include f into the first-step RHS, performing spatial derivation on u<sup>n</sup> and not on  u<sup>n</sup>+f<sup>n+1</sup> &Delta; t.
I thought this has some effect on the wall gradient because there the (otherwise uniform) forcing is not applied.
I reckon this also boils down to the forcing term being very small (smaller than say O(&Delta; t<sup>2</sup>) for AB2).

kind regards,
Paolo
