### ISSUE TITLE
regarding flow over backward step

### ISSUE THREAD

**Issue by ArpitDs** [xcompact3d/Incompact3d#4]
Hello everyone,
Greeting ! Pleased to see new version of code.

I have been trying to simulate flow over backward step , i intend to give nclx1=nclnx=2,ncly1=nclny=2,
and periodic in z.

Any suggestion on how to modify B.C and initial condition ?

**Comment by ArpitDs** [comment]
Thanks Ricardo, I started from periodic hill
But my question was more in regards of how I need to modify inflow-outflow and initial conditions.
Currently I am giving constant velocity above step height as inflow, outflow is convective similar to cylinder case,(I have also modified .prm file for take convective vel input), and i have initialized flow to zero inside the step and some value elsewhere.

I have also commented channel routine

But the velocity is diverging after few time steps , is there anything else that I need to do?

**Comment by ricardofrantz** [comment]
We changed the numbers of the temporal integration routines. Please have a look if you are using the right one.

**Comment by fschuch** [comment]
Dear ArpitDs,

Do you need y-stretching in your configuration?
If not, did you change istret to 0 on prm? It is also important not compile with the compilation flag -DSTRETCHING at Makefile.

Please, let us know if it solves your problem.

**Comment by fschuch** [comment]
Another idea,

When using inflow/outflow in x-direction, the code has a flow control in subroutine pre_correc (navier.f90) to make sure that the influx flow rate is equal to outflux. 

Considering that you have the backward step at the inlet, it may be a problem for you because of the artificial velocity field inside IBM using the Lagrangian interpolator (ivirt=2 and ilag=1 ar prm). Can you please try with ivirt=1 and ilag=0?

**Comment by ArpitDs** [comment]
Thank you for your suggestions, I will implement these things and let you know

**Comment by ArpitDs** [comment]
Dear  fschuch and Ricardo, i have carried out LES of the backward step and it seems to be working fine.
Thank you for your valuable suggestions

Arpit
